# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.2.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _PyZyla
else:
    import _PyZyla

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _PyZyla.delete_SwigPyIterator

    def value(self):
        return _PyZyla.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _PyZyla.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _PyZyla.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _PyZyla.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _PyZyla.SwigPyIterator_equal(self, x)

    def copy(self):
        return _PyZyla.SwigPyIterator_copy(self)

    def next(self):
        return _PyZyla.SwigPyIterator_next(self)

    def __next__(self):
        return _PyZyla.SwigPyIterator___next__(self)

    def previous(self):
        return _PyZyla.SwigPyIterator_previous(self)

    def advance(self, n):
        return _PyZyla.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _PyZyla.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _PyZyla.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _PyZyla.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _PyZyla.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _PyZyla.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _PyZyla.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _PyZyla:
_PyZyla.SwigPyIterator_swigregister(SwigPyIterator)
class A3C(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyZyla.A3C_swiginit(self, _PyZyla.new_A3C(*args))

    def setVerbose(self, flag):
        return _PyZyla.A3C_setVerbose(self, flag)

    def setFrameLimit(self, limit):
        return _PyZyla.A3C_setFrameLimit(self, limit)

    def setOutputPath(self, path):
        return _PyZyla.A3C_setOutputPath(self, path)

    def getFrameLimit(self):
        return _PyZyla.A3C_getFrameLimit(self)

    def getOutputPath(self):
        return _PyZyla.A3C_getOutputPath(self)

    def start(self):
        return _PyZyla.A3C_start(self)

    def stop(self):
        return _PyZyla.A3C_stop(self)

    def getAcquireFPS(self):
        return _PyZyla.A3C_getAcquireFPS(self)

    def getProcessFPS(self):
        return _PyZyla.A3C_getProcessFPS(self)

    def getWriteFPS(self):
        return _PyZyla.A3C_getWriteFPS(self)

    def getProcessQueueSize(self):
        return _PyZyla.A3C_getProcessQueueSize(self)

    def getWriteQueueSize(self):
        return _PyZyla.A3C_getWriteQueueSize(self)

    def getAcquireCount(self):
        return _PyZyla.A3C_getAcquireCount(self)

    def isRunning(self):
        return _PyZyla.A3C_isRunning(self)

    def isMonitoring(self):
        return _PyZyla.A3C_isMonitoring(self)
    __swig_destroy__ = _PyZyla.delete_A3C

# Register A3C in _PyZyla:
_PyZyla.A3C_swigregister(A3C)
class Track(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _PyZyla.Track_swiginit(self, _PyZyla.new_Track(*args))

    def getStart(self):
        return _PyZyla.Track_getStart(self)

    def getEnd(self):
        return _PyZyla.Track_getEnd(self)

    def isBinned(self):
        return _PyZyla.Track_isBinned(self)

    def setStart(self, value):
        return _PyZyla.Track_setStart(self, value)

    def setEnd(self, value):
        return _PyZyla.Track_setEnd(self, value)

    def setBinned(self, value):
        return _PyZyla.Track_setBinned(self, value)
    __swig_destroy__ = _PyZyla.delete_Track

# Register Track in _PyZyla:
_PyZyla.Track_swigregister(Track)
class Zyla(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, index):
        _PyZyla.Zyla_swiginit(self, _PyZyla.new_Zyla(index))
    __swig_destroy__ = _PyZyla.delete_Zyla

    def capturePipeline(self):
        return _PyZyla.Zyla_capturePipeline(self)

    def getInt(self, feature):
        return _PyZyla.Zyla_getInt(self, feature)

    def setInt(self, feature, value):
        return _PyZyla.Zyla_setInt(self, feature, value)

    def getIntMin(self, feature):
        return _PyZyla.Zyla_getIntMin(self, feature)

    def getIntMax(self, feature):
        return _PyZyla.Zyla_getIntMax(self, feature)

    def getBool(self, feature):
        return _PyZyla.Zyla_getBool(self, feature)

    def setBool(self, feature, value):
        return _PyZyla.Zyla_setBool(self, feature, value)

    def getFloat(self, feature):
        return _PyZyla.Zyla_getFloat(self, feature)

    def getFloatMin(self, feature):
        return _PyZyla.Zyla_getFloatMin(self, feature)

    def getFloatMax(self, feature):
        return _PyZyla.Zyla_getFloatMax(self, feature)

    def setFloat(self, feature, value):
        return _PyZyla.Zyla_setFloat(self, feature, value)

    def getEnumInt(self, feature):
        return _PyZyla.Zyla_getEnumInt(self, feature)

    def setEnumInt(self, feature, index):
        return _PyZyla.Zyla_setEnumInt(self, feature, index)

    def getEnum(self, feature):
        return _PyZyla.Zyla_getEnum(self, feature)

    def getString(self, feature):
        return _PyZyla.Zyla_getString(self, feature)

    def setEnum(self, feature, value):
        return _PyZyla.Zyla_setEnum(self, feature, value)

    def command(self, feature):
        return _PyZyla.Zyla_command(self, feature)

    def getEnumOptions(self, feature):
        return _PyZyla.Zyla_getEnumOptions(self, feature)

    def queueBuffer(self, *args):
        return _PyZyla.Zyla_queueBuffer(self, *args)

    def awaitBuffer(self, timeout, size):
        return _PyZyla.Zyla_awaitBuffer(self, timeout, size)

    def acquireRaw(self, timeout, size):
        return _PyZyla.Zyla_acquireRaw(self, timeout, size)

    def getAccumulateCount(self):
        return _PyZyla.Zyla_getAccumulateCount(self)

    def setAccumulateCount(self, value):
        return _PyZyla.Zyla_setAccumulateCount(self, value)

    def getAccumulateCountMin(self):
        return _PyZyla.Zyla_getAccumulateCountMin(self)

    def getAccumulateCountMax(self):
        return _PyZyla.Zyla_getAccumulateCountMax(self)

    def acquisitionStart(self):
        return _PyZyla.Zyla_acquisitionStart(self)

    def acquisitionStop(self):
        return _PyZyla.Zyla_acquisitionStop(self)

    def isAlternatingReadoutDirection(self):
        return _PyZyla.Zyla_isAlternatingReadoutDirection(self)

    def setAlternatingReadoutDirection(self, value):
        return _PyZyla.Zyla_setAlternatingReadoutDirection(self, value)

    def getAOIBinning(self):
        return _PyZyla.Zyla_getAOIBinning(self)

    def setAOIBinning(self, index):
        return _PyZyla.Zyla_setAOIBinning(self, index)

    def getAOIBinningOptions(self):
        return _PyZyla.Zyla_getAOIBinningOptions(self)

    def getAOIHBin(self):
        return _PyZyla.Zyla_getAOIHBin(self)

    def setAOIHBin(self, value):
        return _PyZyla.Zyla_setAOIHBin(self, value)

    def getAOIHBinMin(self):
        return _PyZyla.Zyla_getAOIHBinMin(self)

    def getAOIHBinMax(self):
        return _PyZyla.Zyla_getAOIHBinMax(self)

    def getAOIHeight(self):
        return _PyZyla.Zyla_getAOIHeight(self)

    def setAOIHeight(self, value):
        return _PyZyla.Zyla_setAOIHeight(self, value)

    def getAOIHeightMin(self):
        return _PyZyla.Zyla_getAOIHeightMin(self)

    def getAOIHeightMax(self):
        return _PyZyla.Zyla_getAOIHeightMax(self)

    def getAOILayout(self):
        return _PyZyla.Zyla_getAOILayout(self)

    def setAOILayout(self, index):
        return _PyZyla.Zyla_setAOILayout(self, index)

    def getAOILayoutOptions(self):
        return _PyZyla.Zyla_getAOILayoutOptions(self)

    def getAOILeft(self):
        return _PyZyla.Zyla_getAOILeft(self)

    def setAOILeft(self, value):
        return _PyZyla.Zyla_setAOILeft(self, value)

    def getAOILeftMin(self):
        return _PyZyla.Zyla_getAOILeftMin(self)

    def getAOILeftMax(self):
        return _PyZyla.Zyla_getAOILeftMax(self)

    def getAOIStride(self):
        return _PyZyla.Zyla_getAOIStride(self)

    def setAOIStride(self, value):
        return _PyZyla.Zyla_setAOIStride(self, value)

    def getAOIStrideMin(self):
        return _PyZyla.Zyla_getAOIStrideMin(self)

    def getAOIStrideMax(self):
        return _PyZyla.Zyla_getAOIStrideMax(self)

    def getAOITop(self):
        return _PyZyla.Zyla_getAOITop(self)

    def setAOITop(self, value):
        return _PyZyla.Zyla_setAOITop(self, value)

    def getAOITopMin(self):
        return _PyZyla.Zyla_getAOITopMin(self)

    def getAOITopMax(self):
        return _PyZyla.Zyla_getAOITopMax(self)

    def getAOIVBin(self):
        return _PyZyla.Zyla_getAOIVBin(self)

    def setAOIVBin(self, value):
        return _PyZyla.Zyla_setAOIVBin(self, value)

    def getAOIVBinMin(self):
        return _PyZyla.Zyla_getAOIVBinMin(self)

    def getAOIVBinMax(self):
        return _PyZyla.Zyla_getAOIVBinMax(self)

    def getAOIWidth(self):
        return _PyZyla.Zyla_getAOIWidth(self)

    def setAOIWidth(self, value):
        return _PyZyla.Zyla_setAOIWidth(self, value)

    def getAOIWidthMin(self):
        return _PyZyla.Zyla_getAOIWidthMin(self)

    def getAOIWidthMax(self):
        return _PyZyla.Zyla_getAOIWidthMax(self)

    def getAuxiliaryOutSource(self):
        return _PyZyla.Zyla_getAuxiliaryOutSource(self)

    def setAuxiliaryOutSource(self, index):
        return _PyZyla.Zyla_setAuxiliaryOutSource(self, index)

    def getAuxiliaryOutSourceOptions(self):
        return _PyZyla.Zyla_getAuxiliaryOutSourceOptions(self)

    def getAuxOutSourceTwo(self):
        return _PyZyla.Zyla_getAuxOutSourceTwo(self)

    def setAuxOutSourceTwo(self, index):
        return _PyZyla.Zyla_setAuxOutSourceTwo(self, index)

    def getAuxOutSourceTwoOptions(self):
        return _PyZyla.Zyla_getAuxOutSourceTwoOptions(self)

    def getBaseline(self):
        return _PyZyla.Zyla_getBaseline(self)

    def setBaseline(self, value):
        return _PyZyla.Zyla_setBaseline(self, value)

    def getBaselineMin(self):
        return _PyZyla.Zyla_getBaselineMin(self)

    def getBaselineMax(self):
        return _PyZyla.Zyla_getBaselineMax(self)

    def getBitDepth(self):
        return _PyZyla.Zyla_getBitDepth(self)

    def setBitDepth(self, index):
        return _PyZyla.Zyla_setBitDepth(self, index)

    def getBitDepthOptions(self):
        return _PyZyla.Zyla_getBitDepthOptions(self)

    def getBufferOverflowEvent(self):
        return _PyZyla.Zyla_getBufferOverflowEvent(self)

    def setBufferOverflowEvent(self, value):
        return _PyZyla.Zyla_setBufferOverflowEvent(self, value)

    def getBufferOverflowEventMin(self):
        return _PyZyla.Zyla_getBufferOverflowEventMin(self)

    def getBufferOverflowEventMax(self):
        return _PyZyla.Zyla_getBufferOverflowEventMax(self)

    def getBytesPerPixel(self):
        return _PyZyla.Zyla_getBytesPerPixel(self)

    def setBytesPerPixel(self, value):
        return _PyZyla.Zyla_setBytesPerPixel(self, value)

    def getBytesPerPixelMin(self):
        return _PyZyla.Zyla_getBytesPerPixelMin(self)

    def getBytesPerPixelMax(self):
        return _PyZyla.Zyla_getBytesPerPixelMax(self)

    def isCameraAcquiring(self):
        return _PyZyla.Zyla_isCameraAcquiring(self)

    def setCameraAcquiring(self, value):
        return _PyZyla.Zyla_setCameraAcquiring(self, value)

    def isCameraPresent(self):
        return _PyZyla.Zyla_isCameraPresent(self)

    def setCameraPresent(self, value):
        return _PyZyla.Zyla_setCameraPresent(self, value)

    def getControllerID(self):
        return _PyZyla.Zyla_getControllerID(self)

    def getCoolerPower(self):
        return _PyZyla.Zyla_getCoolerPower(self)

    def setCoolerPower(self, value):
        return _PyZyla.Zyla_setCoolerPower(self, value)

    def getCoolerPowerMin(self):
        return _PyZyla.Zyla_getCoolerPowerMin(self)

    def getCoolerPowerMax(self):
        return _PyZyla.Zyla_getCoolerPowerMax(self)

    def getCycleMode(self):
        return _PyZyla.Zyla_getCycleMode(self)

    def setCycleMode(self, index):
        return _PyZyla.Zyla_setCycleMode(self, index)

    def getCycleModeOptions(self):
        return _PyZyla.Zyla_getCycleModeOptions(self)

    def getDeviceCount(self):
        return _PyZyla.Zyla_getDeviceCount(self)

    def setDeviceCount(self, value):
        return _PyZyla.Zyla_setDeviceCount(self, value)

    def getDeviceCountMin(self):
        return _PyZyla.Zyla_getDeviceCountMin(self)

    def getDeviceCountMax(self):
        return _PyZyla.Zyla_getDeviceCountMax(self)

    def getDeviceVideoIndex(self):
        return _PyZyla.Zyla_getDeviceVideoIndex(self)

    def setDeviceVideoIndex(self, value):
        return _PyZyla.Zyla_setDeviceVideoIndex(self, value)

    def getDeviceVideoIndexMin(self):
        return _PyZyla.Zyla_getDeviceVideoIndexMin(self)

    def getDeviceVideoIndexMax(self):
        return _PyZyla.Zyla_getDeviceVideoIndexMax(self)

    def getElectronicShutteringMode(self):
        return _PyZyla.Zyla_getElectronicShutteringMode(self)

    def setElectronicShutteringMode(self, index):
        return _PyZyla.Zyla_setElectronicShutteringMode(self, index)

    def getElectronicShutteringModeOptions(self):
        return _PyZyla.Zyla_getElectronicShutteringModeOptions(self)

    def isEventEnable(self):
        return _PyZyla.Zyla_isEventEnable(self)

    def setEventEnable(self, value):
        return _PyZyla.Zyla_setEventEnable(self, value)

    def getEventSelector(self):
        return _PyZyla.Zyla_getEventSelector(self)

    def setEventSelector(self, index):
        return _PyZyla.Zyla_setEventSelector(self, index)

    def getEventSelectorOptions(self):
        return _PyZyla.Zyla_getEventSelectorOptions(self)

    def getEventsMissedEvent(self):
        return _PyZyla.Zyla_getEventsMissedEvent(self)

    def setEventsMissedEvent(self, value):
        return _PyZyla.Zyla_setEventsMissedEvent(self, value)

    def getEventsMissedEventMin(self):
        return _PyZyla.Zyla_getEventsMissedEventMin(self)

    def getEventsMissedEventMax(self):
        return _PyZyla.Zyla_getEventsMissedEventMax(self)

    def getExposedPixelHeight(self):
        return _PyZyla.Zyla_getExposedPixelHeight(self)

    def setExposedPixelHeight(self, value):
        return _PyZyla.Zyla_setExposedPixelHeight(self, value)

    def getExposedPixelHeightMin(self):
        return _PyZyla.Zyla_getExposedPixelHeightMin(self)

    def getExposedPixelHeightMax(self):
        return _PyZyla.Zyla_getExposedPixelHeightMax(self)

    def getExposureEndEvent(self):
        return _PyZyla.Zyla_getExposureEndEvent(self)

    def setExposureEndEvent(self, value):
        return _PyZyla.Zyla_setExposureEndEvent(self, value)

    def getExposureEndEventMin(self):
        return _PyZyla.Zyla_getExposureEndEventMin(self)

    def getExposureEndEventMax(self):
        return _PyZyla.Zyla_getExposureEndEventMax(self)

    def getExposureStartEvent(self):
        return _PyZyla.Zyla_getExposureStartEvent(self)

    def setExposureStartEvent(self, value):
        return _PyZyla.Zyla_setExposureStartEvent(self, value)

    def getExposureStartEventMin(self):
        return _PyZyla.Zyla_getExposureStartEventMin(self)

    def getExposureStartEventMax(self):
        return _PyZyla.Zyla_getExposureStartEventMax(self)

    def getExposureTime(self):
        return _PyZyla.Zyla_getExposureTime(self)

    def setExposureTime(self, value):
        return _PyZyla.Zyla_setExposureTime(self, value)

    def getExposureTimeMin(self):
        return _PyZyla.Zyla_getExposureTimeMin(self)

    def getExposureTimeMax(self):
        return _PyZyla.Zyla_getExposureTimeMax(self)

    def getExternalTriggerDelay(self):
        return _PyZyla.Zyla_getExternalTriggerDelay(self)

    def setExternalTriggerDelay(self, value):
        return _PyZyla.Zyla_setExternalTriggerDelay(self, value)

    def getExternalTriggerDelayMin(self):
        return _PyZyla.Zyla_getExternalTriggerDelayMin(self)

    def getExternalTriggerDelayMax(self):
        return _PyZyla.Zyla_getExternalTriggerDelayMax(self)

    def getFanSpeed(self):
        return _PyZyla.Zyla_getFanSpeed(self)

    def setFanSpeed(self, index):
        return _PyZyla.Zyla_setFanSpeed(self, index)

    def getFanSpeedOptions(self):
        return _PyZyla.Zyla_getFanSpeedOptions(self)

    def isFastAOIFrameRateEnable(self):
        return _PyZyla.Zyla_isFastAOIFrameRateEnable(self)

    def setFastAOIFrameRateEnable(self, value):
        return _PyZyla.Zyla_setFastAOIFrameRateEnable(self, value)

    def getFrameCount(self):
        return _PyZyla.Zyla_getFrameCount(self)

    def setFrameCount(self, value):
        return _PyZyla.Zyla_setFrameCount(self, value)

    def getFrameCountMin(self):
        return _PyZyla.Zyla_getFrameCountMin(self)

    def getFrameCountMax(self):
        return _PyZyla.Zyla_getFrameCountMax(self)

    def getFrameRate(self):
        return _PyZyla.Zyla_getFrameRate(self)

    def setFrameRate(self, value):
        return _PyZyla.Zyla_setFrameRate(self, value)

    def getFrameRateMin(self):
        return _PyZyla.Zyla_getFrameRateMin(self)

    def getFrameRateMax(self):
        return _PyZyla.Zyla_getFrameRateMax(self)

    def isFullAOIControl(self):
        return _PyZyla.Zyla_isFullAOIControl(self)

    def setFullAOIControl(self, value):
        return _PyZyla.Zyla_setFullAOIControl(self, value)

    def getImageSizeBytes(self):
        return _PyZyla.Zyla_getImageSizeBytes(self)

    def setImageSizeBytes(self, value):
        return _PyZyla.Zyla_setImageSizeBytes(self, value)

    def getImageSizeBytesMin(self):
        return _PyZyla.Zyla_getImageSizeBytesMin(self)

    def getImageSizeBytesMax(self):
        return _PyZyla.Zyla_getImageSizeBytesMax(self)

    def isIOInvert(self):
        return _PyZyla.Zyla_isIOInvert(self)

    def setIOInvert(self, value):
        return _PyZyla.Zyla_setIOInvert(self, value)

    def getIOSelector(self):
        return _PyZyla.Zyla_getIOSelector(self)

    def setIOSelector(self, index):
        return _PyZyla.Zyla_setIOSelector(self, index)

    def getIOSelectorOptions(self):
        return _PyZyla.Zyla_getIOSelectorOptions(self)

    def getLineScanSpeed(self):
        return _PyZyla.Zyla_getLineScanSpeed(self)

    def setLineScanSpeed(self, value):
        return _PyZyla.Zyla_setLineScanSpeed(self, value)

    def getLineScanSpeedMin(self):
        return _PyZyla.Zyla_getLineScanSpeedMin(self)

    def getLineScanSpeedMax(self):
        return _PyZyla.Zyla_getLineScanSpeedMax(self)

    def getLogLevel(self):
        return _PyZyla.Zyla_getLogLevel(self)

    def setLogLevel(self, index):
        return _PyZyla.Zyla_setLogLevel(self, index)

    def getLogLevelOptions(self):
        return _PyZyla.Zyla_getLogLevelOptions(self)

    def getLongExposureTransition(self):
        return _PyZyla.Zyla_getLongExposureTransition(self)

    def setLongExposureTransition(self, value):
        return _PyZyla.Zyla_setLongExposureTransition(self, value)

    def getLongExposureTransitionMin(self):
        return _PyZyla.Zyla_getLongExposureTransitionMin(self)

    def getLongExposureTransitionMax(self):
        return _PyZyla.Zyla_getLongExposureTransitionMax(self)

    def getMaxInterfaceTransferRate(self):
        return _PyZyla.Zyla_getMaxInterfaceTransferRate(self)

    def setMaxInterfaceTransferRate(self, value):
        return _PyZyla.Zyla_setMaxInterfaceTransferRate(self, value)

    def getMaxInterfaceTransferRateMin(self):
        return _PyZyla.Zyla_getMaxInterfaceTransferRateMin(self)

    def getMaxInterfaceTransferRateMax(self):
        return _PyZyla.Zyla_getMaxInterfaceTransferRateMax(self)

    def isMetadataEnable(self):
        return _PyZyla.Zyla_isMetadataEnable(self)

    def setMetadataEnable(self, value):
        return _PyZyla.Zyla_setMetadataEnable(self, value)

    def isMetadataFrame(self):
        return _PyZyla.Zyla_isMetadataFrame(self)

    def setMetadataFrame(self, value):
        return _PyZyla.Zyla_setMetadataFrame(self, value)

    def isMetadataTimestamp(self):
        return _PyZyla.Zyla_isMetadataTimestamp(self)

    def setMetadataTimestamp(self, value):
        return _PyZyla.Zyla_setMetadataTimestamp(self, value)

    def isMultitrackBinned(self):
        return _PyZyla.Zyla_isMultitrackBinned(self)

    def setMultitrackBinned(self, value):
        return _PyZyla.Zyla_setMultitrackBinned(self, value)

    def getMultitrackCount(self):
        return _PyZyla.Zyla_getMultitrackCount(self)

    def setMultitrackCount(self, value):
        return _PyZyla.Zyla_setMultitrackCount(self, value)

    def getMultitrackCountMin(self):
        return _PyZyla.Zyla_getMultitrackCountMin(self)

    def getMultitrackCountMax(self):
        return _PyZyla.Zyla_getMultitrackCountMax(self)

    def getMultitrackEnd(self):
        return _PyZyla.Zyla_getMultitrackEnd(self)

    def setMultitrackEnd(self, value):
        return _PyZyla.Zyla_setMultitrackEnd(self, value)

    def getMultitrackEndMin(self):
        return _PyZyla.Zyla_getMultitrackEndMin(self)

    def getMultitrackEndMax(self):
        return _PyZyla.Zyla_getMultitrackEndMax(self)

    def getMultitrackSelector(self):
        return _PyZyla.Zyla_getMultitrackSelector(self)

    def setMultitrackSelector(self, value):
        return _PyZyla.Zyla_setMultitrackSelector(self, value)

    def getMultitrackSelectorMin(self):
        return _PyZyla.Zyla_getMultitrackSelectorMin(self)

    def getMultitrackSelectorMax(self):
        return _PyZyla.Zyla_getMultitrackSelectorMax(self)

    def getMultitrackStart(self):
        return _PyZyla.Zyla_getMultitrackStart(self)

    def setMultitrackStart(self, value):
        return _PyZyla.Zyla_setMultitrackStart(self, value)

    def getMultitrackStartMin(self):
        return _PyZyla.Zyla_getMultitrackStartMin(self)

    def getMultitrackStartMax(self):
        return _PyZyla.Zyla_getMultitrackStartMax(self)

    def getTracks(self):
        return _PyZyla.Zyla_getTracks(self)

    def setTracks(self, tracks):
        return _PyZyla.Zyla_setTracks(self, tracks)

    def isOverlap(self):
        return _PyZyla.Zyla_isOverlap(self)

    def setOverlap(self, value):
        return _PyZyla.Zyla_setOverlap(self, value)

    def getPixelEncoding(self):
        return _PyZyla.Zyla_getPixelEncoding(self)

    def setPixelEncoding(self, index):
        return _PyZyla.Zyla_setPixelEncoding(self, index)

    def getPixelEncodingOptions(self):
        return _PyZyla.Zyla_getPixelEncodingOptions(self)

    def getPixelHeight(self):
        return _PyZyla.Zyla_getPixelHeight(self)

    def setPixelHeight(self, value):
        return _PyZyla.Zyla_setPixelHeight(self, value)

    def getPixelHeightMin(self):
        return _PyZyla.Zyla_getPixelHeightMin(self)

    def getPixelHeightMax(self):
        return _PyZyla.Zyla_getPixelHeightMax(self)

    def getPixelReadoutRate(self):
        return _PyZyla.Zyla_getPixelReadoutRate(self)

    def setPixelReadoutRate(self, index):
        return _PyZyla.Zyla_setPixelReadoutRate(self, index)

    def getPixelReadoutRateOptions(self):
        return _PyZyla.Zyla_getPixelReadoutRateOptions(self)

    def getPixelWidth(self):
        return _PyZyla.Zyla_getPixelWidth(self)

    def setPixelWidth(self, value):
        return _PyZyla.Zyla_setPixelWidth(self, value)

    def getPixelWidthMin(self):
        return _PyZyla.Zyla_getPixelWidthMin(self)

    def getPixelWidthMax(self):
        return _PyZyla.Zyla_getPixelWidthMax(self)

    def getReadoutTime(self):
        return _PyZyla.Zyla_getReadoutTime(self)

    def setReadoutTime(self, value):
        return _PyZyla.Zyla_setReadoutTime(self, value)

    def getReadoutTimeMin(self):
        return _PyZyla.Zyla_getReadoutTimeMin(self)

    def getReadoutTimeMax(self):
        return _PyZyla.Zyla_getReadoutTimeMax(self)

    def isRollingShutterGlobalClear(self):
        return _PyZyla.Zyla_isRollingShutterGlobalClear(self)

    def setRollingShutterGlobalClear(self, value):
        return _PyZyla.Zyla_setRollingShutterGlobalClear(self, value)

    def getRowNExposureEndEvent(self):
        return _PyZyla.Zyla_getRowNExposureEndEvent(self)

    def setRowNExposureEndEvent(self, value):
        return _PyZyla.Zyla_setRowNExposureEndEvent(self, value)

    def getRowNExposureEndEventMin(self):
        return _PyZyla.Zyla_getRowNExposureEndEventMin(self)

    def getRowNExposureEndEventMax(self):
        return _PyZyla.Zyla_getRowNExposureEndEventMax(self)

    def getRowNExposureStartEvent(self):
        return _PyZyla.Zyla_getRowNExposureStartEvent(self)

    def setRowNExposureStartEvent(self, value):
        return _PyZyla.Zyla_setRowNExposureStartEvent(self, value)

    def getRowNExposureStartEventMin(self):
        return _PyZyla.Zyla_getRowNExposureStartEventMin(self)

    def getRowNExposureStartEventMax(self):
        return _PyZyla.Zyla_getRowNExposureStartEventMax(self)

    def isScanSpeedControlEnable(self):
        return _PyZyla.Zyla_isScanSpeedControlEnable(self)

    def setScanSpeedControlEnable(self, value):
        return _PyZyla.Zyla_setScanSpeedControlEnable(self, value)

    def isSensorCooling(self):
        return _PyZyla.Zyla_isSensorCooling(self)

    def setSensorCooling(self, value):
        return _PyZyla.Zyla_setSensorCooling(self, value)

    def getSensorHeight(self):
        return _PyZyla.Zyla_getSensorHeight(self)

    def setSensorHeight(self, value):
        return _PyZyla.Zyla_setSensorHeight(self, value)

    def getSensorHeightMin(self):
        return _PyZyla.Zyla_getSensorHeightMin(self)

    def getSensorHeightMax(self):
        return _PyZyla.Zyla_getSensorHeightMax(self)

    def getSensorReadoutMode(self):
        return _PyZyla.Zyla_getSensorReadoutMode(self)

    def setSensorReadoutMode(self, index):
        return _PyZyla.Zyla_setSensorReadoutMode(self, index)

    def getSensorReadoutModeOptions(self):
        return _PyZyla.Zyla_getSensorReadoutModeOptions(self)

    def getSensorTemperature(self):
        return _PyZyla.Zyla_getSensorTemperature(self)

    def setSensorTemperature(self, value):
        return _PyZyla.Zyla_setSensorTemperature(self, value)

    def getSensorTemperatureMin(self):
        return _PyZyla.Zyla_getSensorTemperatureMin(self)

    def getSensorTemperatureMax(self):
        return _PyZyla.Zyla_getSensorTemperatureMax(self)

    def getSensorWidth(self):
        return _PyZyla.Zyla_getSensorWidth(self)

    def setSensorWidth(self, value):
        return _PyZyla.Zyla_setSensorWidth(self, value)

    def getSensorWidthMin(self):
        return _PyZyla.Zyla_getSensorWidthMin(self)

    def getSensorWidthMax(self):
        return _PyZyla.Zyla_getSensorWidthMax(self)

    def getSerialNumber(self):
        return _PyZyla.Zyla_getSerialNumber(self)

    def getShutterMode(self):
        return _PyZyla.Zyla_getShutterMode(self)

    def setShutterMode(self, index):
        return _PyZyla.Zyla_setShutterMode(self, index)

    def getShutterModeOptions(self):
        return _PyZyla.Zyla_getShutterModeOptions(self)

    def getShutterOutputMode(self):
        return _PyZyla.Zyla_getShutterOutputMode(self)

    def setShutterOutputMode(self, index):
        return _PyZyla.Zyla_setShutterOutputMode(self, index)

    def getShutterOutputModeOptions(self):
        return _PyZyla.Zyla_getShutterOutputModeOptions(self)

    def getShutterTransferTime(self):
        return _PyZyla.Zyla_getShutterTransferTime(self)

    def setShutterTransferTime(self, value):
        return _PyZyla.Zyla_setShutterTransferTime(self, value)

    def getShutterTransferTimeMin(self):
        return _PyZyla.Zyla_getShutterTransferTimeMin(self)

    def getShutterTransferTimeMax(self):
        return _PyZyla.Zyla_getShutterTransferTimeMax(self)

    def getSimplePreAmpGainControl(self):
        return _PyZyla.Zyla_getSimplePreAmpGainControl(self)

    def setSimplePreAmpGainControl(self, index):
        return _PyZyla.Zyla_setSimplePreAmpGainControl(self, index)

    def getSimplePreAmpGainControlOptions(self):
        return _PyZyla.Zyla_getSimplePreAmpGainControlOptions(self)

    def softwareTrigger(self):
        return _PyZyla.Zyla_softwareTrigger(self)

    def getSoftwareVersion(self):
        return _PyZyla.Zyla_getSoftwareVersion(self)

    def isSpuriousNoiseFilter(self):
        return _PyZyla.Zyla_isSpuriousNoiseFilter(self)

    def setSpuriousNoiseFilter(self, value):
        return _PyZyla.Zyla_setSpuriousNoiseFilter(self, value)

    def isStaticBlemishCorrection(self):
        return _PyZyla.Zyla_isStaticBlemishCorrection(self)

    def setStaticBlemishCorrection(self, value):
        return _PyZyla.Zyla_setStaticBlemishCorrection(self, value)

    def getTemperatureControl(self):
        return _PyZyla.Zyla_getTemperatureControl(self)

    def setTemperatureControl(self, index):
        return _PyZyla.Zyla_setTemperatureControl(self, index)

    def getTemperatureControlOptions(self):
        return _PyZyla.Zyla_getTemperatureControlOptions(self)

    def getTemperatureStatus(self):
        return _PyZyla.Zyla_getTemperatureStatus(self)

    def setTemperatureStatus(self, index):
        return _PyZyla.Zyla_setTemperatureStatus(self, index)

    def getTemperatureStatusOptions(self):
        return _PyZyla.Zyla_getTemperatureStatusOptions(self)

    def getTimestampClock(self):
        return _PyZyla.Zyla_getTimestampClock(self)

    def setTimestampClock(self, value):
        return _PyZyla.Zyla_setTimestampClock(self, value)

    def getTimestampClockMin(self):
        return _PyZyla.Zyla_getTimestampClockMin(self)

    def getTimestampClockMax(self):
        return _PyZyla.Zyla_getTimestampClockMax(self)

    def getTimestampClockFrequency(self):
        return _PyZyla.Zyla_getTimestampClockFrequency(self)

    def setTimestampClockFrequency(self, value):
        return _PyZyla.Zyla_setTimestampClockFrequency(self, value)

    def getTimestampClockFrequencyMin(self):
        return _PyZyla.Zyla_getTimestampClockFrequencyMin(self)

    def getTimestampClockFrequencyMax(self):
        return _PyZyla.Zyla_getTimestampClockFrequencyMax(self)

    def timestampClockReset(self):
        return _PyZyla.Zyla_timestampClockReset(self)

    def getTriggerMode(self):
        return _PyZyla.Zyla_getTriggerMode(self)

    def setTriggerMode(self, index):
        return _PyZyla.Zyla_setTriggerMode(self, index)

    def getTriggerModeOptions(self):
        return _PyZyla.Zyla_getTriggerModeOptions(self)

    def isVerticallyCentreAOI(self):
        return _PyZyla.Zyla_isVerticallyCentreAOI(self)

    def setVerticallyCentreAOI(self, value):
        return _PyZyla.Zyla_setVerticallyCentreAOI(self, value)

# Register Zyla in _PyZyla:
_PyZyla.Zyla_swigregister(Zyla)

